/* eslint-disable */
// @ts-nocheck
/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.11.7
 *
 */
import type { IFluenceClient as IFluenceClient$$, CallParams as CallParams$$ } from '@fluencelabs/js-client.api';
import {
    v5_callFunction as callFunction$$,
    v5_registerService as registerService$$,
} from '@fluencelabs/js-client.api';
    


// Services

// Functions
export const test_script = `
                    (xor
                     (seq
                      (seq
                       (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                       (new $a
                        (seq
                         (seq
                          (seq
                           (seq
                            (seq
                             (par
                              (call %init_peer_id% ("json" "obj") ["decider" []] GetWorkersInfoDeals_obj)
                              (seq
                               (new $option-inline
                                (seq
                                 (seq
                                  (seq
                                   (new $array-inline
                                    (seq
                                     (seq
                                      (call %init_peer_id% ("json" "obj") ["hostId" "12D3KooWJDiLFLmWstcFpAofWkYJzuvwuquNTQQkB9xzKjRyqqFJ" "spellId" "9f279a9d-3e38-4c46-8665-e80c8473fbdd" "workerId" "12D3KooWMz7FJcdzRzZeBg9izvhRxdNY1cyArL4iy2nsfS2PP8n4"] GetWorkersInfoHostsDeciderInstallationSpells_obj)
                                      (ap GetWorkersInfoHostsDeciderInstallationSpells_obj $array-inline)
                                     )
                                     (canon %init_peer_id% $array-inline  #array-inline-0)
                                    )
                                   )
                                   (call %init_peer_id% ("json" "obj") ["definition" "bafkreiao74du7pvpnz2sxypsbo4f7lo4rxiskl6vtwz3slebk54y3aip74" "installationSpells" #array-inline-0 "relayId" "12D3KooWJDiLFLmWstcFpAofWkYJzuvwuquNTQQkB9xzKjRyqqFJ" "timestamp" "2023-07-19T17:46:56.556Z"] GetWorkersInfoHostsDecider_obj)
                                  )
                                  (xor
                                   (ap GetWorkersInfoHostsDecider_obj $option-inline)
                                   (null)
                                  )
                                 )
                                 (canon %init_peer_id% $option-inline  #option-inline-0)
                                )
                               )
                               (call %init_peer_id% ("json" "obj") ["decider" #option-inline-0] GetWorkersInfoHosts_obj)
                              )
                             )
                             (call %init_peer_id% ("json" "obj") ["deals" GetWorkersInfoDeals_obj "hosts" GetWorkersInfoHosts_obj] GetWorkersInfo_obj)
                            )
                            (call -relay- ("op" "noop") [])
                           )
                           (xor
                            (seq
                             (seq
                              (seq
                               (new $option-inline-1
                                (seq
                                 (xor
                                  (ap "wtf" $option-inline-1)
                                  (null)
                                 )
                                 (canon GetWorkersInfo_obj.$.hosts.decider.[0].relayId $option-inline-1  #option-inline-1-0)
                                )
                               )
                               (call GetWorkersInfo_obj.$.hosts.decider.[0].relayId ("op" "identity") [#option-inline-1-0] identity)
                              )
                              (ap identity $a)
                             )
                             (call -relay- ("op" "noop") [])
                            )
                            (seq
                             (call -relay- ("op" "noop") [])
                             (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                            )
                           )
                          )
                          (canon %init_peer_id% $a  #-a-fix-0)
                         )
                         (ap #-a-fix-0 -a-flat-0)
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [-a-flat-0])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                    )
    `
 

export function test(
    config?: {ttl?: number}
): Promise<string | null | null>;

export function test(
    peer: IFluenceClient$$,
    config?: {ttl?: number}
): Promise<string | null | null>;

export function test(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "test",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "option",
                    "type" : {
                        "tag" : "option",
                        "type" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        test_script
    )
}

export const get_logs_script = `
                    (xor
                     (seq
                      (seq
                       (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                       (new $all_logs
                        (seq
                         (seq
                          (seq
                           (seq
                            (seq
                             (par
                              (call %init_peer_id% ("json" "obj") ["decider" []] GetWorkersInfoDeals_obj)
                              (seq
                               (new $option-inline
                                (seq
                                 (seq
                                  (seq
                                   (new $array-inline
                                    (seq
                                     (seq
                                      (call %init_peer_id% ("json" "obj") ["hostId" "12D3KooWJDiLFLmWstcFpAofWkYJzuvwuquNTQQkB9xzKjRyqqFJ" "spellId" "9f279a9d-3e38-4c46-8665-e80c8473fbdd" "workerId" "12D3KooWMz7FJcdzRzZeBg9izvhRxdNY1cyArL4iy2nsfS2PP8n4"] GetWorkersInfoHostsDeciderInstallationSpells_obj)
                                      (ap GetWorkersInfoHostsDeciderInstallationSpells_obj $array-inline)
                                     )
                                     (canon %init_peer_id% $array-inline  #array-inline-0)
                                    )
                                   )
                                   (call %init_peer_id% ("json" "obj") ["definition" "bafkreiao74du7pvpnz2sxypsbo4f7lo4rxiskl6vtwz3slebk54y3aip74" "installationSpells" #array-inline-0 "relayId" "12D3KooWJDiLFLmWstcFpAofWkYJzuvwuquNTQQkB9xzKjRyqqFJ" "timestamp" "2023-07-19T17:46:56.556Z"] GetWorkersInfoHostsDecider_obj)
                                  )
                                  (xor
                                   (ap GetWorkersInfoHostsDecider_obj $option-inline)
                                   (null)
                                  )
                                 )
                                 (canon %init_peer_id% $option-inline  #option-inline-0)
                                )
                               )
                               (call %init_peer_id% ("json" "obj") ["decider" #option-inline-0] GetWorkersInfoHosts_obj)
                              )
                             )
                             (call %init_peer_id% ("json" "obj") ["deals" GetWorkersInfoDeals_obj "hosts" GetWorkersInfoHosts_obj] GetWorkersInfo_obj)
                            )
                            (call -relay- ("op" "noop") [])
                           )
                           (xor
                            (seq
                             (fold GetWorkersInfo_obj.$.hosts.decider.[0].installationSpells spell-0
                              (seq
                               (seq
                                (call spell-0.$.hostId ("op" "noop") [])
                                (xor
                                 (seq
                                  (seq
                                   (call spell-0.$.workerId (spell-0.$.spellId "list_get_strings") ["logs"] logs)
                                   (ap logs.$.strings $all_logs)
                                  )
                                  (call spell-0.$.hostId ("op" "noop") [])
                                 )
                                 (seq
                                  (seq
                                   (seq
                                    (seq
                                     (call spell-0.$.hostId ("op" "noop") [])
                                     (call -relay- ("op" "noop") [])
                                    )
                                    (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                                   )
                                   (call -relay- ("op" "noop") [])
                                  )
                                  (call spell-0.$.hostId ("op" "noop") [])
                                 )
                                )
                               )
                               (next spell-0)
                              )
                             )
                             (call -relay- ("op" "noop") [])
                            )
                            (seq
                             (call -relay- ("op" "noop") [])
                             (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                            )
                           )
                          )
                          (canon %init_peer_id% $all_logs  #-all_logs-fix-0)
                         )
                         (ap #-all_logs-fix-0 -all_logs-flat-0)
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [-all_logs-flat-0])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
                    )
    `
 

export function get_logs(
    config?: {ttl?: number}
): Promise<string[][]>;

export function get_logs(
    peer: IFluenceClient$$,
    config?: {ttl?: number}
): Promise<string[][]>;

export function get_logs(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "get_logs",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "array",
                    "type" : {
                        "tag" : "array",
                        "type" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        get_logs_script
    )
}

export const inspect_script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (seq
                            (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                            (par
                             (call %init_peer_id% ("json" "obj") ["decider" []] GetWorkersInfoDeals_obj)
                             (seq
                              (new $option-inline
                               (seq
                                (seq
                                 (seq
                                  (new $array-inline
                                   (seq
                                    (seq
                                     (call %init_peer_id% ("json" "obj") ["hostId" "12D3KooWJDiLFLmWstcFpAofWkYJzuvwuquNTQQkB9xzKjRyqqFJ" "spellId" "9f279a9d-3e38-4c46-8665-e80c8473fbdd" "workerId" "12D3KooWMz7FJcdzRzZeBg9izvhRxdNY1cyArL4iy2nsfS2PP8n4"] GetWorkersInfoHostsDeciderInstallationSpells_obj)
                                     (ap GetWorkersInfoHostsDeciderInstallationSpells_obj $array-inline)
                                    )
                                    (canon %init_peer_id% $array-inline  #array-inline-0)
                                   )
                                  )
                                  (call %init_peer_id% ("json" "obj") ["definition" "bafkreiao74du7pvpnz2sxypsbo4f7lo4rxiskl6vtwz3slebk54y3aip74" "installationSpells" #array-inline-0 "relayId" "12D3KooWJDiLFLmWstcFpAofWkYJzuvwuquNTQQkB9xzKjRyqqFJ" "timestamp" "2023-07-19T17:46:56.556Z"] GetWorkersInfoHostsDecider_obj)
                                 )
                                 (xor
                                  (ap GetWorkersInfoHostsDecider_obj $option-inline)
                                  (null)
                                 )
                                )
                                (canon %init_peer_id% $option-inline  #option-inline-0)
                               )
                              )
                              (call %init_peer_id% ("json" "obj") ["decider" #option-inline-0] GetWorkersInfoHosts_obj)
                             )
                            )
                           )
                           (call %init_peer_id% ("json" "obj") ["deals" GetWorkersInfoDeals_obj "hosts" GetWorkersInfoHosts_obj] GetWorkersInfo_obj)
                          )
                          (ap GetWorkersInfo_obj.$.hosts GetWorkersInfo_obj_flat)
                         )
                         (ap GetWorkersInfo_obj_flat.$.decider GetWorkersInfo_obj_flat_flat)
                        )
                        (ap GetWorkersInfo_obj_flat_flat.$.[0].installationSpells GetWorkersInfo_obj_flat_flat_flat)
                       )
                       (fold GetWorkersInfo_obj_flat_flat_flat spell-0
                        (seq
                         (seq
                          (seq
                           (call -relay- ("op" "noop") [])
                           (call spell-0.$.hostId ("op" "noop") [])
                          )
                          (xor
                           (seq
                            (seq
                             (seq
                              (call spell-0.$.workerId ("srv" "list") [] list)
                              (call spell-0.$.hostId ("op" "noop") [])
                             )
                             (call -relay- ("op" "noop") [])
                            )
                            (xor
                             (call %init_peer_id% ("run-console" "print") [list])
                             (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                            )
                           )
                           (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                          )
                         )
                         (next spell-0)
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") ["OK"])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
                    )
    `
 

export function inspect(
    config?: {ttl?: number}
): Promise<string>;

export function inspect(
    peer: IFluenceClient$$,
    config?: {ttl?: number}
): Promise<string>;

export function inspect(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "inspect",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "scalar",
                    "name" : "string"
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        inspect_script
    )
}

export const test_join_script = `
                    (xor
                     (seq
                      (seq
                       (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                       (new $all_input
                        (new $result
                         (seq
                          (seq
                           (seq
                            (seq
                             (xor
                              (seq
                               (seq
                                (new $array-inline
                                 (seq
                                  (seq
                                   (seq
                                    (seq
                                     (seq
                                      (seq
                                       (seq
                                        (seq
                                         (seq
                                          (seq
                                           (seq
                                            (seq
                                             (seq
                                              (seq
                                               (seq
                                                (seq
                                                 (seq
                                                  (seq
                                                   (seq
                                                    (seq
                                                     (seq
                                                      (ap "[1]" $array-inline)
                                                      (ap "[2]" $array-inline)
                                                     )
                                                     (ap "[3]" $array-inline)
                                                    )
                                                    (ap "[4]" $array-inline)
                                                   )
                                                   (ap "[5]" $array-inline)
                                                  )
                                                  (ap "[6]" $array-inline)
                                                 )
                                                 (ap "[7]" $array-inline)
                                                )
                                                (ap "[8]" $array-inline)
                                               )
                                               (ap "[9]" $array-inline)
                                              )
                                              (ap "[10]" $array-inline)
                                             )
                                             (ap "[11]" $array-inline)
                                            )
                                            (ap "[12]" $array-inline)
                                           )
                                           (ap "[13]" $array-inline)
                                          )
                                          (ap "[14]" $array-inline)
                                         )
                                         (ap "[15]" $array-inline)
                                        )
                                        (ap "[16]" $array-inline)
                                       )
                                       (ap "[17]" $array-inline)
                                      )
                                      (ap "[18]" $array-inline)
                                     )
                                     (ap "[19]" $array-inline)
                                    )
                                    (ap "[20]" $array-inline)
                                   )
                                   (ap "[21]" $array-inline)
                                  )
                                  (canon -relay- $array-inline  #array-inline-0)
                                 )
                                )
                                (call -relay- ("op" "identity") [#array-inline-0] identity)
                               )
                               (ap identity $all_input)
                              )
                              (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                             )
                             (par
                              (seq
                               (canon %init_peer_id% $all_input  #all_input_canon)
                               (fold #all_input_canon inp-0
                                (par
                                 (par
                                  (fold inp-0 i-0
                                   (par
                                    (seq
                                     (seq
                                      (call %init_peer_id% ("json" "parse") [i-0] parse)
                                      (ap parse $result)
                                     )
                                     (call %init_peer_id% ("run-console" "print") ["parsed"])
                                    )
                                    (next i-0)
                                   )
                                   (never)
                                  )
                                  (null)
                                 )
                                 (next inp-0)
                                )
                                (never)
                               )
                              )
                              (null)
                             )
                            )
                            (new $result_test
                             (seq
                              (seq
                               (seq
                                (call %init_peer_id% ("math" "add") [10 1] result_incr)
                                (fold $result result_fold_var
                                 (seq
                                  (seq
                                   (ap result_fold_var $result_test)
                                   (canon %init_peer_id% $result_test  #result_iter_canon)
                                  )
                                  (xor
                                   (match #result_iter_canon.length result_incr
                                    (null)
                                   )
                                   (next result_fold_var)
                                  )
                                 )
                                 (never)
                                )
                               )
                               (canon %init_peer_id% $result_test  #result_result_canon)
                              )
                              (ap #result_result_canon result_gate)
                             )
                            )
                           )
                           (canon %init_peer_id% $result  #-result-fix-0)
                          )
                          (ap #-result-fix-0 -result-flat-0)
                         )
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [-result-flat-0])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                    )
    `
 

export function test_join(
    config?: {ttl?: number}
): Promise<string[]>;

export function test_join(
    peer: IFluenceClient$$,
    config?: {ttl?: number}
): Promise<string[]>;

export function test_join(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "test_join",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "array",
                    "type" : {
                        "tag" : "scalar",
                        "name" : "string"
                    }
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        test_join_script
    )
}

export const joined_deals_script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (seq
                            (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                            (par
                             (call %init_peer_id% ("json" "obj") ["decider" []] GetWorkersInfoDeals_obj)
                             (seq
                              (new $option-inline
                               (seq
                                (seq
                                 (seq
                                  (new $array-inline
                                   (seq
                                    (seq
                                     (call %init_peer_id% ("json" "obj") ["hostId" "12D3KooWJDiLFLmWstcFpAofWkYJzuvwuquNTQQkB9xzKjRyqqFJ" "spellId" "9f279a9d-3e38-4c46-8665-e80c8473fbdd" "workerId" "12D3KooWMz7FJcdzRzZeBg9izvhRxdNY1cyArL4iy2nsfS2PP8n4"] GetWorkersInfoHostsDeciderInstallationSpells_obj)
                                     (ap GetWorkersInfoHostsDeciderInstallationSpells_obj $array-inline)
                                    )
                                    (canon %init_peer_id% $array-inline  #array-inline-0)
                                   )
                                  )
                                  (call %init_peer_id% ("json" "obj") ["definition" "bafkreiao74du7pvpnz2sxypsbo4f7lo4rxiskl6vtwz3slebk54y3aip74" "installationSpells" #array-inline-0 "relayId" "12D3KooWJDiLFLmWstcFpAofWkYJzuvwuquNTQQkB9xzKjRyqqFJ" "timestamp" "2023-07-19T17:46:56.556Z"] GetWorkersInfoHostsDecider_obj)
                                 )
                                 (xor
                                  (ap GetWorkersInfoHostsDecider_obj $option-inline)
                                  (null)
                                 )
                                )
                                (canon %init_peer_id% $option-inline  #option-inline-0)
                               )
                              )
                              (call %init_peer_id% ("json" "obj") ["decider" #option-inline-0] GetWorkersInfoHosts_obj)
                             )
                            )
                           )
                           (call %init_peer_id% ("json" "obj") ["deals" GetWorkersInfoDeals_obj "hosts" GetWorkersInfoHosts_obj] GetWorkersInfo_obj)
                          )
                          (ap GetWorkersInfo_obj.$.hosts GetWorkersInfo_obj_flat)
                         )
                         (ap GetWorkersInfo_obj_flat.$.decider GetWorkersInfo_obj_flat_flat)
                        )
                        (ap GetWorkersInfo_obj_flat_flat.$.[0].installationSpells GetWorkersInfo_obj_flat_flat_flat)
                       )
                       (fold GetWorkersInfo_obj_flat_flat_flat spell-0
                        (seq
                         (seq
                          (seq
                           (call -relay- ("op" "noop") [])
                           (call spell-0.$.hostId ("op" "noop") [])
                          )
                          (xor
                           (seq
                            (seq
                             (seq
                              (new $joined_deals
                               (seq
                                (seq
                                 (seq
                                  (call spell-0.$.workerId ("decider" "list_get_strings") ["joined_deals"] list)
                                  (xor
                                   (match list.$.success false
                                    (xor
                                     (seq
                                      (seq
                                       (seq
                                        (new $array-inline-1
                                         (seq
                                          (seq
                                           (ap "can't restrive joined deals" $array-inline-1)
                                           (ap list.$.error $array-inline-1)
                                          )
                                          (canon spell-0.$.workerId $array-inline-1  #array-inline-1-0)
                                         )
                                        )
                                        (par
                                         (call spell-0.$.workerId ("run-console" "print") ["decider" #array-inline-1-0])
                                         (null)
                                        )
                                       )
                                       (call spell-0.$.workerId ("json" "stringify") [#array-inline-1-0] msg_str)
                                      )
                                      (call spell-0.$.workerId ("decider" "list_push_string") ["logs" msg_str])
                                     )
                                     (seq
                                      (seq
                                       (seq
                                        (seq
                                         (call spell-0.$.hostId ("op" "noop") [])
                                         (call -relay- ("op" "noop") [])
                                        )
                                        (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                                       )
                                       (call -relay- ("op" "noop") [])
                                      )
                                      (call spell-0.$.hostId ("op" "noop") [])
                                     )
                                    )
                                   )
                                   (fold list.$.strings joined_deal_str-0
                                    (seq
                                     (xor
                                      (seq
                                       (call spell-0.$.workerId ("json" "parse") [joined_deal_str-0] joined_deal)
                                       (ap joined_deal $joined_deals)
                                      )
                                      (seq
                                       (seq
                                        (seq
                                         (new $array-inline-2
                                          (seq
                                           (seq
                                            (seq
                                             (ap "error parsing JoinedDeal" $array-inline-2)
                                             (ap joined_deal_str-0 $array-inline-2)
                                            )
                                            (ap %last_error% $array-inline-2)
                                           )
                                           (canon spell-0.$.workerId $array-inline-2  #array-inline-2-0)
                                          )
                                         )
                                         (par
                                          (call spell-0.$.workerId ("run-console" "print") ["decider" #array-inline-2-0])
                                          (null)
                                         )
                                        )
                                        (call spell-0.$.workerId ("json" "stringify") [#array-inline-2-0] msg_str-0)
                                       )
                                       (call spell-0.$.workerId ("decider" "list_push_string") ["logs" msg_str-0])
                                      )
                                     )
                                     (next joined_deal_str-0)
                                    )
                                   )
                                  )
                                 )
                                 (canon spell-0.$.workerId $joined_deals  #-joined_deals-fix-0)
                                )
                                (ap #-joined_deals-fix-0 -joined_deals-flat-0)
                               )
                              )
                              (call spell-0.$.hostId ("op" "noop") [])
                             )
                             (call -relay- ("op" "noop") [])
                            )
                            (xor
                             (call %init_peer_id% ("run-console" "print") [-joined_deals-flat-0])
                             (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                            )
                           )
                           (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                          )
                         )
                         (next spell-0)
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") ["OK"])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 5])
                    )
    `
 

export function joined_deals(
    config?: {ttl?: number}
): Promise<string>;

export function joined_deals(
    peer: IFluenceClient$$,
    config?: {ttl?: number}
): Promise<string>;

export function joined_deals(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "joined_deals",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "scalar",
                    "name" : "string"
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        joined_deals_script
    )
}

export const remove_script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (seq
                            (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                            (par
                             (call %init_peer_id% ("json" "obj") ["decider" []] GetWorkersInfoDeals_obj)
                             (seq
                              (new $option-inline
                               (seq
                                (seq
                                 (seq
                                  (new $array-inline
                                   (seq
                                    (seq
                                     (call %init_peer_id% ("json" "obj") ["hostId" "12D3KooWJDiLFLmWstcFpAofWkYJzuvwuquNTQQkB9xzKjRyqqFJ" "spellId" "9f279a9d-3e38-4c46-8665-e80c8473fbdd" "workerId" "12D3KooWMz7FJcdzRzZeBg9izvhRxdNY1cyArL4iy2nsfS2PP8n4"] GetWorkersInfoHostsDeciderInstallationSpells_obj)
                                     (ap GetWorkersInfoHostsDeciderInstallationSpells_obj $array-inline)
                                    )
                                    (canon %init_peer_id% $array-inline  #array-inline-0)
                                   )
                                  )
                                  (call %init_peer_id% ("json" "obj") ["definition" "bafkreiao74du7pvpnz2sxypsbo4f7lo4rxiskl6vtwz3slebk54y3aip74" "installationSpells" #array-inline-0 "relayId" "12D3KooWJDiLFLmWstcFpAofWkYJzuvwuquNTQQkB9xzKjRyqqFJ" "timestamp" "2023-07-19T17:46:56.556Z"] GetWorkersInfoHostsDecider_obj)
                                 )
                                 (xor
                                  (ap GetWorkersInfoHostsDecider_obj $option-inline)
                                  (null)
                                 )
                                )
                                (canon %init_peer_id% $option-inline  #option-inline-0)
                               )
                              )
                              (call %init_peer_id% ("json" "obj") ["decider" #option-inline-0] GetWorkersInfoHosts_obj)
                             )
                            )
                           )
                           (call %init_peer_id% ("json" "obj") ["deals" GetWorkersInfoDeals_obj "hosts" GetWorkersInfoHosts_obj] GetWorkersInfo_obj)
                          )
                          (ap GetWorkersInfo_obj.$.hosts GetWorkersInfo_obj_flat)
                         )
                         (ap GetWorkersInfo_obj_flat.$.decider GetWorkersInfo_obj_flat_flat)
                        )
                        (ap GetWorkersInfo_obj_flat_flat.$.[0].installationSpells GetWorkersInfo_obj_flat_flat_flat)
                       )
                       (fold GetWorkersInfo_obj_flat_flat_flat spell-0
                        (seq
                         (seq
                          (call -relay- ("op" "noop") [])
                          (xor
                           (seq
                            (call spell-0.$.hostId ("worker" "remove") [spell-0.$.workerId])
                            (call -relay- ("op" "noop") [])
                           )
                           (seq
                            (call -relay- ("op" "noop") [])
                            (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                           )
                          )
                         )
                         (next spell-0)
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") ["OK"])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                    )
    `
 

export function remove(
    config?: {ttl?: number}
): Promise<string>;

export function remove(
    peer: IFluenceClient$$,
    config?: {ttl?: number}
): Promise<string>;

export function remove(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "remove",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "scalar",
                    "name" : "string"
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        remove_script
    )
}

/* eslint-enable */